### PR TITLE
Updating the bash-completion package to be compatible with ZSH.

### PR DESCRIPTION
**Pull request by yafshar**
This update facilitates command-line usage of the helper utilities or ZSH.
ZSH comes with bashcompinit that creates the same functionality as complete
builtin function in bash.

### CODE REVIEW

**Comment by ellio167** [comment]
@yafshar Let's look at how the `git` project does this.

(at least on homebrew) they seem to install like this:

./etc/bash_completion.d
./etc/bash_completion.d/git-completion.bash
./share/zsh/site-functions/git-completion.bash
./share/zsh/site-functions/_git

**Comment by ellio167** [comment]
@yafshar Take a look at my changes and let me know what you think.

**Comment by yafshar** [comment]
@ellio167 It sounds good to me.

Also, I think there are some minor mistakes in the collections-management.bash.in,
(I might be wrong!)

Line 100, I think mo is wrong and it should be "portable model (pm)" so  instead of  "md|mo|sm", it should be "md|pm|sm"

Line 120, it should be 
            opts="--force  --sudo"
Line 122, it should be 
            opts="--interactive  --sudo"
Line 143, it should be 
            opts="--force  --sudo"
Line 145, it should be 
            opts="--interactive  --sudo"

**Comment by ellio167** [comment]
@yafshar Thanks for the careful look.  In fact, I think these are all OK.  For historical reasons our two-letter code for Portable Models is `MO` (https://openkim.org/doc/schema/kim-ids/)

For the rest, the `--force` and `--interactive` options are mutually exclusive (as indicate by the `|`, which follows the http://docopt.org conventions).

I'll merge this in soon.

**Comment by yafshar** [comment]
@ellio167 Thanks for the information.

**Pull request merged**
