### PR TITLE
Work toward Travis-CI to GitHub Actions transiton

### PR DESCRIPTION
**Pull request by ellio167**
This will address #63

### CODE REVIEW

**Comment by ellio167** [comment]
@yafshar We can use this branch/PR to work on the CI transition.

I think the first step is to simply convert what we have, as-is (as much as possible), for Travis-CI over to GitHub Actions.

After that, I would also like to think about how we can be good citizens and organize the CI so that it is not quite so redundant as we have now. (I've made a small step in that direction in b07a679, where I added options to select various parts of the current CI tests) Maybe we should always be doing work in a feature branch and have more limited CI for those branches and then have "complete" CI just on the `devel` branch.  I'm open to ideas here; we can discuss.

**Comment by yafshar** [comment]
@ellio167 To work on the CI transition, I found [act](https://github.com/nektos/act) very interesting. It helps to run GitHub Actions locally.

**Comment by ellio167** [comment]
> @ellio167 To work on the CI transition, I found [act](https://github.com/nektos/act) very interesting. It helps to run GitHub Actions locally.

Yes, very cool!  Thanks for pointing to this.

**Comment by ellio167** [comment]
Closes #63

**Pull request merged**
