### PR TITLE
Added C++ bindings for Log Push/Pop DefaultPrintFunction

### PR DESCRIPTION
**Pull request by ellio167**
Provide mechanism for changing the way the Log objects actually print the messages.

This would, I think for example, allow an MPI program to write and use its own routine that could forward log strings to the zero rank processor for writing to a single file, etc.

### CODE REVIEW

**Comment by ellio167** [comment]
@yafshar Let's see if this can resolve the issue with mpi parallel debugging you mentioned.

C and Fortran bindings still need to be implemented, but I want to confirm that this solves the issue first.

ping: @tadmor @dskarls 

I'm imagining a use case something like this...

```cpp
int MyPrint(std::string msg)
{
  int me = -1;
  MPI_Comm_rank(MPI_COMM_WORLD, &me);
  if (me == 0)
  {
    fwrite(..., msg);
  }
  else
  {
     // send string to head node for write
  }
return false;
}

int main(...)
{
  KIM_Log_PushDefaultPrintFunction(KIM_LANGUAGE_NAME_cpp, &MyPrint);

  // ....
}
```

**Comment by yafshar** [comment]
> @yafshar Let's see if this can resolve the issue with mpi parallel debugging you mentioned.
> 
> C and Fortran bindings still need to be implemented, but I want to confirm that this solves the issue first.
> 
> ping: @tadmor @dskarls
> 
> I'm imagining a use case something like this...
> 
> ```c++
> int MyPrint(std::string msg)
> {
>   int me = -1;
>   MPI_Comm_rank(MPI_COMM_WORLD, &me);
>   if (me == 0)
>   {
>     fwrite(..., msg);
>   }
>   else
>   {
>      // send string to head node for write
>   }
> return false;
> }
> 
> int main(...)
> {
>   KIM_Log_PushDefaultPrintFunction(KIM_LANGUAGE_NAME_cpp, &MyPrint);
> 
>   // ....
> }
> ```

@ellio167 Potentially, it can solve most of the debugging problem. However, it still has an issue. It is limited to the `MPI_COMM_WORLD` communicator, and it is not possible to use the communicator from the simulator. But let me write an example and try it there first.

**Comment by yafshar** [comment]
@ellio167 I can not make the update from #https://github.com/openkim/kim-api/pull/46/commits/e2d0ea6b430ff9f5b0099bdc5516cb8c8ab4482b and your latest push to work with [LAMMPS](https://github.com/yafshar/lammps/tree/add-default-log-function). It gives me an error `kim_init.cpp:180:3: error: 'KIM_Log_PushDefaultPrintFunction' was not declared in this scope`. Can you please give it a try.

**Comment by ellio167** [comment]
You probably need to `#include “KIM_Log.h”`

**Comment by yafshar** [comment]
> You probably need to `#include “KIM_Log.h”`

@ellio167 thanks, that was the issue.

**Comment by yafshar** [comment]
> You probably need to `#include “KIM_Log.h”`

@ellio167 should this header be part of the `KIM_SimulatorHeaders.h` or you want it to be included for the similar cases? (since the Logverbosty header is included)

**Comment by ellio167** [comment]
> > You probably need to `#include “KIM_Log.h”`
> 
> @ellio167 should this header be part of the `KIM_SimulatorHeaders.h` or you want it to be included separately for the similar cases? (since the Logverbosity header is already included there)

I would leave it as is.  The SimulatorHeaders is meant to be a minimal set that is needed for a simulator.  The DefaultPrintFunction is really an "extra" feature.

**Pull request merged**
