### PR TITLE
Updating the get_password function

### PR DESCRIPTION
**Pull request by yafshar**
Improve the function to restore the settings and trap signals on exit.

### CODE REVIEW

**Comment by ellio167** [comment]
@yafshar I'm getting an `stty: tcsetattr: Input/output error` message if I type `control-c` at the prompt.  I can't seem to figure out the cause/fix.

Also, I prefer the back-ticks for subshell variable expansion as it is (I believe) more portable.

**Comment by yafshar** [comment]
> @yafshar I'm getting an stty: tcsetattr: Input/output error message if I type control-c at the prompt. I can't seem to figure out the cause/fix.
The error message is only explanatory; we can get rid of it by creating some conditional if cases and putting exit in the signal_handler. I make some changes to avoid extra messages in case of interruption. I rather have the message for expressiveness and help to figure out the problem in case of any.

> Also, I prefer the back-ticks for subshell variable expansion as it is (I believe) more portable.
I think backquote command substitution is a bit old-style, but I also like it more
Unfortunately, I do not know how to do a multiline command substitution using backquote.




https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html

**Comment by ellio167** [comment]
How about this.  It look to me like multilne backquote works ok. This seems simpler to me, but maybe I removed some functionality that I didn't understand/follow.  Let me know.

**Comment by yafshar** [comment]
@ellio167  It sounds good. Actually, you are right to remove extra things we do not need the signal `Interrupt` and `Terminate` here. I tested it on my mac and ubuntu on both zsh and bash and it is working perfectly fine for me.

**Comment by ellio167** [comment]
Great!  Thanks.

**Pull request merged**
