### PR TITLE
Re-license to LGPL-2.1-or-later

### PR DESCRIPTION
**Pull request by ellio167**
This PR will implement the process of re-licensing the kim-api package to LGPL-2.1-or-later.  All previous contributors to the package will be assigned as reviewers to indicated their agreement to the re-license.

### CODE REVIEW

**Review by yafshar — APPROVED** [review]
Seems great to me.

**Comment by tadmor** [comment]
Looks good. Approved.

**Review by junghans — APPROVED** [review]
Absolutely, go ahead.

**Review by mjwen — APPROVED** [review]

**Review by dskarls — APPROVED** [review]

**Comment by ellio167** [comment]
@albert-github
@JimMadge 
@t-brink 
@whalen 

I'd like to add you as reviewers to this PR.  I hope you will accept the invite I've sent so we can get everyone's formal approval to the re-licensing of this package.  Thanks!

**Review by JimMadge — APPROVED** [review]
Looks good to me :+1:.

**Review by stukowski — APPROVED** [review]
I agree to the license change.

**Review by whalen — APPROVED** [review]

**Review by t-brink — APPROVED** [review]
I agree with the license change. Thanks for working to improve license compatibility as much as possible.

**Comment by ellio167** [comment]
ping @rbberger @albert-github

**Comment by rbberger** [comment]
Go ahead.

**Pull request merged**
