### PR TITLE
Major refactoring of cmake KIM-API and KIM-API-ITEMS packages

### PR DESCRIPTION
**Pull request by ellio167**
Provide more idiosyncratic cmake behavior

* use export packages
* cleaner package structure
* refactor lots of code into multi-use macros/functions
* eliminate unneeded package variables

### CODE REVIEW

**Comment by ellio167** [comment]
@junghans @rbberger 
I would be quite interested in your review of these changes, if you have the time.
I think I've learned and applied modern cmake usage and convention here, but if you see anything that might be done differently and/or improved, I would like to know!

**Comment by ellio167** [comment]
@stukowski
Would it be possible for you to test this with MinGW and Cygwin?

**Comment by stukowski** [comment]
> @stukowski
> Would it be possible for you to test this with MinGW and Cygwin?

Yes, let me review and test these changes tomorrow.

**Comment by stukowski** [comment]
Please note that branches ``devel`` and ``refactor-cmake-packages`` both currently fail to build under MinGW due to the following change made in an earlier commit:

https://github.com/openkim/kim-api/commit/a1762372fb355dc87279c8498cdf1641ae3f5013#diff-a63183e639d3edddbda0e38f922ca6c2L62-L65

After bringing back these code lines, the code from ``refactor-cmake-packages`` builds fine with MinGW and Cygwin. All CMake tests succeeded, and I've successfully built LAMMPS against an installed version of the KIM API module under MinGW.

**Comment by ellio167** [comment]
> Please note that branches `devel` and `refactor-cmake-packages` both currently fail to build under MinGW due to the following change made in an earlier commit:
> 
> [a176237#diff-a63183e639d3edddbda0e38f922ca6c2L62-L65](https://github.com/openkim/kim-api/commit/a1762372fb355dc87279c8498cdf1641ae3f5013#diff-a63183e639d3edddbda0e38f922ca6c2L62-L65)
> 
> After bringing back these code lines, the code from `refactor-cmake-packages` builds fine with MinGW and Cygwin. All CMake tests succeeded, and I've successfully built LAMMPS against an installed version of the KIM API module under MinGW.

Thanks for checking!  I can put those lines back.  I had not noticed that these were being used for implicit conversions!

I'll also add a case to the CI where it uses  CMAKE_CXX_FLAGS="-DKIM_API_USE_FILESYSTEM_LIBRARY" so that this sort of thing is caught earlier....

**Comment by ellio167** [comment]
> @ellio167 I looked over the code a bit. Seems ok to me. Nice to see everything getting really short in the end. I also verified it still runs on CMake 3.4.
> 
> One thing I did notice was the requirement for XXD. We have something similar in LAMMPS for the GPU package. It's not the most elegant code, but we have a CMake-only XXD replacement. See
> https://github.com/lammps/lammps/blob/master/cmake/Modules/Packages/GPU.cmake#L312
> https://github.com/lammps/lammps/blob/master/cmake/Modules/GenerateBinaryHeader.cmake
> https://github.com/lammps/lammps/blob/master/cmake/Modules/LAMMPSUtils.cmake#L74

Many thanks for the review.  Indeed, I just realized yesterday that the `file(... HEX)` command could be used to remove the `xxd` dependency.  Great to know that LAMMPS also has this as an example I can follow for the implementation.  Thanks for the pointer.

**Comment by junghans** [comment]
Looks nice, can we then reapply https://github.com/lammps/lammps/pull/2018?

**Comment by ellio167** [comment]
> Looks nice, can we then reapply [lammps/lammps#2018](https://github.com/lammps/lammps/pull/2018)?

Yes, once this is merged and v2.2.0 is released.

**Pull request merged**
