### PR TITLE
Extra check

### PR DESCRIPTION
**Pull request by yafshar**
Explicitly initialize the pointers and correct the return behavior.
Mostly through create, and destroy class instances, to prevent used-before-set errors and
their associated undefined behavior in an unpredicted usage behavior or mistakes.

### CODE REVIEW

**Comment by ellio167** [comment]
@yafshar I was wrong.  You will need to rebase this on the current devel branch and force push the update.

**Comment by ellio167** [comment]
@yafshar for code style consistency, I want all pointer comparisons to explicitly use `(ptr == NULL)`  (Eventually, if we move to C++11 we'll change `NULL` to `nulptr`.)  This is, in my opinion, better because it allows for type checking at compile time (doesn't rely on implicit type conversion of a pointer to int).

Please make this change everywhere in your PR and then I'll continue with a review.  (I'd like to work on this today if you can get to it soon.)

**Comment by yafshar** [comment]
> @yafshar for code style consistency, I want all pointer comparisons to explicitly use `(ptr == NULL)` (Eventually, if we move to C++11 we'll change `NULL` to `nulptr`.) This is, in my opinion, better because it allows for type checking at compile time (doesn't rely on implicit type conversion of a pointer to int).
> 
> Please make this change everywhere in your PR and then I'll continue with a review. (I'd like to work on this today if you can get to it soon.)

@ellio167 I did this change in my PR. I change every pointer comparison in my PR to `!= NULL` But, there are other cases in the code that I did not change and they are not following this.

**Comment by ellio167** [comment]
@yafshar Thanks, I'll make a note to work through and change the existing non-confirming cases.

**Comment by ellio167** [comment]
@yafshar You've done something to muck up the PR.  I'm closing this one; please make a new clean PR that is based on the current devel branch?

**Pull request closed without merging**
