### PR TITLE
Function pointers for C and C++

### PR DESCRIPTION
**Pull request by ellio167**
@mjwen, @tadmor, @dskarls 

Hi all, this branch contains changes to the api so that it uses explicit function prototypes for all the model's routines.  There are also prototype definitions for all the callbacks in the KIM_FunctionTypes header file.

This is nice because it makes things more explicit, provides a natural place to document the function prototypes for all the Model routines, and allows the compiler to check that the prototypes for all the model routines are, indeed, correct.

Fortran doesn't have a similar concept of function-type and so there are no changes to the fortran code and such code does not benefit from this feature.  (I guess documentation of the fortran routine interfaces will need to be done in the manual instead of directly in the code.)

I think this is all good, but comments are welcome before I merge it into the main-line development branch.  In particular, Mingjian, I would guess this will have some impact on kimpy...

### CODE REVIEW

**Comment by mjwen** [comment]
Agreed. This makes the registration of model routines more explicit.

Seems this technique is not applied to callbacks provided by simulators, and we still use a void function pointer for callbacks. I understand that the function [SetCallbackPointer](https://github.com/openkim/kim-api/blob/8751e7ed2aba83757d470662a68b1fa2307d52f6/cpp/include/KIM_ComputeArguments.hpp#L73) is supposed to work with any type of callbacks, but is there any mechanism that we enforce the function prototype as well? One naive way (we may not want to do this) is to separate [SetCallbackPointer](https://github.com/openkim/kim-api/blob/8751e7ed2aba83757d470662a68b1fa2307d52f6/cpp/include/KIM_ComputeArguments.hpp#L73) into multiple functions, each for a type of callback.

**Comment by ellio167** [comment]
@mjwen A good question.

However, it has made me realize that using the prototypes in this way forces the functions to be written in the language that the ModelCreate routine is written in.  This could be OK, but it is limiting.  And I did not intend to limit the api in this way.  This all deserves some more thought...

**Comment by mjwen** [comment]
> ... using the prototypes in this way forces the functions to be written in the language that the ModelCreate routine is written in ...

Yes. But if we use function prototype on the model side, we have the same problem, right?  

A related one: with function prototype, compilers can check the correctness of the registered routines at compiling time. Previously (before this PR),  how does it guarantee the registered function is of the correct type? The API do some check at runtime?

**Comment by ellio167** [comment]
There is not a check when the functions are cast to KIM::Function.  There is no getting around this, except as I have done in the latest example updates where I force a check by defining function pointers of the appropriate type.  This requires the user to perform the check in this way, but I think it is the best we can manage (without being restrictive---As soon as we say "all model functions must be written in the same language, someone with come out of the woodwork and want to write them in different languages....)

**Pull request merged**
